import tkinter as tk
from tkinter import ttk
from frame2 import working
class new_frame:
    def new(m):
        m.destroy()
        m=tk.Tk()
        m.geometry('250x400')
        m.resizable(0, 0)
        m.title("Register")
        t_label1 = ttk.Label(master=m, text='Register', font=("Arial", 35))
        t_label1.pack()
        l1=ttk.Label(master=m,text="User name",font=('Arials',10))
        l1.pack()
        r=ttk.Entry(m)
        r.pack(pady=5)
        l2 = ttk.Label(master=m, text="Password", font=('Arials', 10))
        l2.pack()
        r1 = ttk.Entry(m)
        r1.pack(pady=5)
        l2 = ttk.Label(master=m, text="Phone", font=('Arials', 10))
        l2.pack()
        r2 = ttk.Entry(m)
        r2.pack(pady=5)
        l3= ttk.Label(master=m, text="Mail", font=('Arials', 10))
        l3.pack()
        r3 = ttk.Entry(m)
        r3.pack(pady=5)
        l4 = ttk.Label(master=m, text="ID", font=('Arials', 10))
        l4.pack()
        r4 = ttk.Entry(m)
        r4.pack(pady=5)
        b=ttk.Button(master=m,text="enter",command=lambda : working.done(m,r))
        b.pack()
        m.focus()
        m.mainloop()
